### ISSUE TITLE
Skipping rpath

### ISSUE THREAD

**Issue by zeckma-tech** [Zeckmathederg/glfs#11]
Skipping rpath isn't done for GLFS although rpath can be dangerous.

**Comment by zeckma-tech** [comment]
Reading BLFS logs makes it seem as if it's a CMake specific issue. Current tasks:
- Add xinclude for -DCMAKE_SKIP_INSTALL_RPATH
- Find all packages using CMake and don't already have the option
- Add the option for every package using CMake

If more packages require RPATH skipped, then issue will be reopened after closure.

**Comment by zeckma-tech** [comment]
Packages using CMake that don't have the option but should:
- Vulkan-Loader (wrong skip rpath parameter)
- SPIRV-Tools (??? Maybe, not in BLFS but has a lib installed)
- LLVM
- libvdpau-va-gl (??? Maybe, not in BLFS but has a lib installed)
- SPIRV-LLVM-Translator (wrong skip rpath parameter)

Packages using CMake that have the option but not the explanation:
- None have the right option

**Comment by zeckma-tech** [comment]
SPIRV-Tools and libvdpau-va-gl weren't covered in the commit as I am unsure if the switch is required for either of them. LMK if it is required for the two packages.

**Comment by zeckma-tech** [comment]
Closing the issue as completed but will monitor BLFS logs for updates there.

**Comment by xry111** [comment]
> SPIRV-Tools and libvdpau-va-gl weren't covered in the commit as I am unsure if the switch is required for either of them. LMK if it is required for the two packages.

I only removed the unnecessary rpath really appeared in my system.

Some cmake-based packages install w/o rpath despite we don't have -DCMAKE_SKIP_INSTALL_RPATH=ON and I've not touched them (I guess they've made it the default but I'm not sure).

And I've not touched the packages I don't use.

**Comment by zeckma-tech** [comment]
> > SPIRV-Tools and libvdpau-va-gl weren't covered in the commit as I am unsure if the switch is required for either of them. LMK if it is required for the two packages.
> 
> I only removed the unnecessary rpath really appeared in my system.
> 
> Some cmake-based packages install w/o rpath despite we don't have -DCMAKE_SKIP_INSTALL_RPATH=ON and I've not touched them (I guess they've made it the default but I'm not sure).
> 
> And I've not touched the packages I don't use.

Fair enough. Thanks for letting me know!
