### ISSUE TITLE
xcb-util-cursor broken download link

### ISSUE THREAD

**Issue by youdontknowdemo** [Zeckmathederg/glfs#15]
[https://xcb.freedesktop.org/dist/xcb-util-cursor-0.1.5.tar.xz](https://xcb.freedesktop.org/dist/xcb-util-cursor-0.1.5.tar.xz)
[https://github.com/Zeckmathederg/glfs/blob/trunk/shareddeps/dps/x/xcb-util-cursor.xml](https://github.com/Zeckmathederg/glfs/blob/trunk/shareddeps/dps/x/xcb-util-cursor.xml)

**Comment by zeckma-tech** [comment]
It is now fixed, closing. Thanks for reporting. The Gitlab repo for Xorg contains newer versions although only two of them are newer. The newer versions aren't in the standard download repos, however. While possible to get them to work, I'm not going to bother with it quite yet. Sorry bout that. Rendering pages now.
