### ISSUE TITLE
Should elogind be added?

### ISSUE THREAD

**Issue by zeckma-tech** [Zeckmathederg/glfs#20]
More of a discussion rather than issue, but this has caused some confusion among some.

GLFS' packages do not technically require elogind. However, it is a recommended dependency of some and should really be introduced before those packages need to be compiled. It is also needed for any Wayland compositor to work as a backend for Seatd, which right now is compiled without that backend. This is a problem. While the user can be sent to BLFS pages, it is not ideal for elogind and its dependencies not being in the book.

The issue adding elogind in the book which has been why it has not been added yet: it requires many dependencies. The following pipeline goes like this: Linux-PAM -> elogind (man pages will be disabled) -> Shadow (recommended to allow Shadow utils to use PAM) ->  packaging (Python module) -> GLib -> Polkit. Another issue is that these packages can be complicated to install for many different reasons. 

Should elogind be added?

**Comment by bfitzgit23** [comment]
imho yes it would help

**Comment by zeckma-tech** [comment]
I will add it in after I receive a PR from Rahul.

**Comment by zeckma-tech** [comment]
I didn't receive that PR I spoke of but wanted this done sooner than later, so there we go. Added.
