### ISSUE TITLE
problems with the systemd version

### ISSUE THREAD

**Issue by mozgwar** [Zeckmathederg/glfs#23]
Hi,
I'm trying to build the systemd version and I get the following:

Adjusting for revision systemd...
Validating the book...
/home/mathieu/tmp/glfs-systemd-html2.xml:14489: element xref: validity error : IDREF attribute linkend references an unknown ID "elogind"
/home/mathieu/tmp/glfs-systemd-html2.xml:16681: element xref: validity error : IDREF attribute linkend references an unknown ID "elogind"
/home/mathieu/tmp/glfs-systemd-html2.xml:17299: element xref: validity error : IDREF attribute linkend references an unknown ID "elogind"
/home/mathieu/tmp/glfs-systemd-html2.xml:27759: element xref: validity error : IDREF attribute linkend references an unknown ID "elogind"
Document /home/mathieu/tmp/glfs-systemd-html2.xml does not validate
make: *** [Makefile:198: /home/mathieu/tmp/glfs-systemd-full.xml] Error 3

**Comment by zeckma-tech** [comment]
There is no Systemd version, and there won't be either for some time or not at all. This is because LFS Multilib, which most people following the book should read up on, is SysV instead of Systemd.
